export const getFallbackData = () => [
  {
    coinId: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    price: 43250.67,
    marketCap: 847392847392,
    priceChange24h: 2.34,
    image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
    rank: 1,
    lastUpdated: new Date(),
  },
  {
    coinId: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    price: 2650.45,
    marketCap: 318492847392,
    priceChange24h: -1.23,
    image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
    rank: 2,
    lastUpdated: new Date(),
  },
  {
    coinId: "tether",
    name: "Tether",
    symbol: "USDT",
    price: 1.0,
    marketCap: 95847392847,
    priceChange24h: 0.01,
    image: "https://assets.coingecko.com/coins/images/325/large/Tether.png",
    rank: 3,
    lastUpdated: new Date(),
  },
  {
    coinId: "binancecoin",
    name: "BNB",
    symbol: "BNB",
    price: 315.78,
    marketCap: 47392847392,
    priceChange24h: 3.45,
    image:
      "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png",
    rank: 4,
    lastUpdated: new Date(),
  },
  {
    coinId: "solana",
    name: "Solana",
    symbol: "SOL",
    price: 98.45,
    marketCap: 43847392847,
    priceChange24h: 5.67,
    image: "https://assets.coingecko.com/coins/images/4128/large/solana.png",
    rank: 5,
    lastUpdated: new Date(),
  },
  {
    coinId: "ripple",
    name: "XRP",
    symbol: "XRP",
    price: 0.52,
    marketCap: 28847392847,
    priceChange24h: -2.34,
    image:
      "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png",
    rank: 6,
    lastUpdated: new Date(),
  },
  {
    coinId: "usd-coin",
    name: "USDC",
    symbol: "USDC",
    price: 1.0,
    marketCap: 25847392847,
    priceChange24h: -0.01,
    image:
      "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
    rank: 7,
    lastUpdated: new Date(),
  },
  {
    coinId: "staked-ether",
    name: "Lido Staked Ether",
    symbol: "STETH",
    price: 2648.23,
    marketCap: 24847392847,
    priceChange24h: -1.45,
    image:
      "https://assets.coingecko.com/coins/images/13442/large/steth_logo.png",
    rank: 8,
    lastUpdated: new Date(),
  },
  {
    coinId: "cardano",
    name: "Cardano",
    symbol: "ADA",
    price: 0.45,
    marketCap: 15847392847,
    priceChange24h: 1.23,
    image: "https://assets.coingecko.com/coins/images/975/large/cardano.png",
    rank: 9,
    lastUpdated: new Date(),
  },
  {
    coinId: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    price: 0.08,
    marketCap: 11847392847,
    priceChange24h: 4.56,
    image: "https://assets.coingecko.com/coins/images/5/large/dogecoin.png",
    rank: 10,
    lastUpdated: new Date(),
  },
];
